export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const EDIT_TODO_ITEM = 'EDIT_TODO_ITEM';

export const MARK_TODO_ITEM_DONE = 'EDIT_TODO_ITEM';
export const MARK_TODO_ITEM_UNDONE = 'MARK_TODO_ITEM_UNDONE';

export const FILTER_ALL = 'FILTER_ALL';
export const FILTER_DONE = 'FILTER_DONE';
export const FILTER_UNDONE = 'FILTER_UNDONE';
